version: "3"

services:
  apisix:
    image: apache/apisix:2.0-alpine
    # 官网 2.1-alpine 镜像存在ssl无法启动BUG，此处暂用2.0-alpine替代
    #image: apache/apisix:2.1-alpine
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      # 此处分别以80、443替换原配置文件中的9080、9443以便直接配置使用
      - "80:9080/tcp"
      - "443:9443/tcp"
      #- "9080:9080/tcp"
      #- "9443:9443/tcp"
    networks:
      apisix:
        ipv4_address: 172.18.5.11

  etcd:
    image: bitnami/etcd:3.4.9
    user: root
    restart: always
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:
        ipv4_address: 172.18.5.10

  apisix-dashboard:
    container_name: apisix-dashboard
    # 由于官方未提供镜像，此处暂使用自建镜像
    image: registry.cn-shanghai.aliyuncs.com/qwxingzhe/apisix-dashboard:2.1-master-20201210
    ports:
      - 9000:9000
    volumes:
      - ./apisix-dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    networks:
      apisix:
        ipv4_address: 172.18.5.18

networks:
  apisix:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.0.0/16